# E:\程序\CSC490\TweetVerify\src\model\prompt_only_llm.py
import modal
import pandas as pd
from transformers import AutoTokenizer, AutoModelForCausalLM
import torch, textwrap, os
from sklearn.metrics import precision_recall_fscore_support, accuracy_score
from io import BytesIO

from datetime import datetime
import logging
from tqdm import tqdm
from pathlib import Path


app = modal.App("tweetverify-prompt-llm")

# --- Local file paths ---
PROJECT_ROOT = Path(__file__).resolve().parents[2]
DATA_DIR = PROJECT_ROOT / "datalake" / "curated"

AI_LOCAL = DATA_DIR / "llm" / "ai_generated.csv"
HUMAN_LOCAL = DATA_DIR / "twitter" / "high_quality_human.csv"

LOCAL_OUTPUT_DIR = PROJECT_ROOT / "src" / "outputs"
os.makedirs(LOCAL_OUTPUT_DIR, exist_ok=True)

# --- Modal image with dependencies ---
image = (
    modal.Image.debian_slim()
    .pip_install(
        "torch", "transformers", "accelerate", "bitsandbytes",
        "sentencepiece", "scikit-learn", "pandas"
    )
)

@app.function(
    image=image,
    gpu="A100",
    timeout=3600, 
)
def classify_dataset(combined_bytes: bytes):
    """Run Qwen2.5-7B-Instruct to classify tweets (prompt-only)."""
    df = pd.read_csv(BytesIO(combined_bytes))
    df = df.sample(frac=1, random_state=42).reset_index(drop=True)

    MODEL = "Qwen/Qwen2.5-7B-Instruct"
    tokenizer = AutoTokenizer.from_pretrained(MODEL, use_fast=False)
    model = AutoModelForCausalLM.from_pretrained(
        MODEL,
        device_map="auto",
        dtype=torch.bfloat16,
    )

    preds, outputs = [], []

    logging.basicConfig(
        format="%(asctime)s - %(message)s",
        level=logging.INFO,
        datefmt="%H:%M:%S"
    )

    logging.info(f"🚀 Starting classification on {len(df)} samples...")

    for i, row in enumerate(tqdm(df.itertuples(), total=len(df), desc="Classifying")):
        text, gold = row.text, row.label
        prompt = textwrap.dedent(f"""
        You are a fact-checking judge.
        Decide whether the following tweet was written by a human or generated by an AI system.
        Answer with exactly one word: AI or Human.

        Tweet:
        {text}
        """).strip()

        inputs = tokenizer(prompt, return_tensors="pt").to(model.device)
        out = model.generate(**inputs, max_new_tokens=10, do_sample=False)
        reply = tokenizer.decode(out[0][inputs["input_ids"].shape[1]:], skip_special_tokens=True)
        reply_clean = reply.replace("\n", " ").strip()

        # interpret reply
        if "AI" in reply_clean and "Human" not in reply_clean:
            pred = 1
        elif "Human" in reply_clean and "AI" not in reply_clean:
            pred = 0
        else:
            pred = -1  # uncertain / unparseable

        correct = (pred == gold)
        status = "✅ Correct" if correct else ("❌ Wrong" if pred in [0, 1] else "⚠️ Unclear")
        logging.info(f"[{i+1}/{len(df)}] Label={gold} → Pred={pred} | {status}")

        preds.append(pred)
        outputs.append(reply_clean)

    df["prediction"] = preds
    df["raw_output"] = outputs

    valid_df = df[df["prediction"] >= 0]
    y_true, y_pred = valid_df["label"], valid_df["prediction"]
    prec, rec, f1, _ = precision_recall_fscore_support(y_true, y_pred, average="binary")
    acc = accuracy_score(y_true, y_pred)

    metrics = {
        "accuracy": acc,
        "precision": prec,
        "recall": rec,
        "f1": f1,
        "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "samples": len(df),
        "valid": len(valid_df),
    }

    # Save predictions with timestamp
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    out_csv = f"predictions_modal_{ts}.csv"
    df.to_csv(out_csv, index=False)
    return {"metrics": metrics, "csv_bytes": open(out_csv, "rb").read()}


@app.local_entrypoint()
def main():
    """Uploads 1000 AI + 1000 Human samples with fixed seed, runs inference remotely."""
    ai_df = pd.read_csv(AI_CSV).sample(n=1000, random_state=42)
    human_df = pd.read_csv(HUMAN_CSV).sample(n=1000, random_state=42)

    combined_df = pd.concat([ai_df, human_df], ignore_index=True)
    combined_buf = BytesIO()
    combined_df.to_csv(combined_buf, index=False)
    combined_bytes = combined_buf.getvalue()

    result = classify_dataset.remote(combined_bytes)
    metrics = result["metrics"]

    # Print metrics nicely
    print("\n=== Evaluation Metrics ===")
    for k, v in metrics.items():
        if k not in ["timestamp", "samples", "valid"]:
            print(f"{k:>10s}: {v:.4f}")

    # Save predictions locally with timestamp
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    out_path = os.path.join(LOCAL_OUTPUT_DIR, f"predictions_modal_{ts}.csv")
    with open(out_path, "wb") as f:
        f.write(result["csv_bytes"])

    print(f"\nPredictions saved to: {out_path}")

    # Log metrics to cumulative file
    metrics_path = os.path.join(LOCAL_OUTPUT_DIR, "metrics_log.txt")
    with open(metrics_path, "a", encoding="utf-8") as f:
        f.write(
            f"[{metrics['timestamp']}] "
            f"samples={metrics['samples']} valid={metrics['valid']} | "
            f"Acc={metrics['accuracy']:.4f} Prec={metrics['precision']:.4f} "
            f"Rec={metrics['recall']:.4f} F1={metrics['f1']:.4f}\n"
        )

    print(f"Metrics appended to: {metrics_path}")
